SELECT
    F.PRODUCT_ID,
    F.PRODUCT_NAME,
    SUM(F.PRICE * S.AMOUNT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT F
JOIN
    FOOD_ORDER S
ON
    F.PRODUCT_ID = S.PRODUCT_ID
WHERE
    TO_CHAR(S.PRODUCE_DATE,'YYYY-MM') = '2022-05'
GROUP BY
    F.PRODUCT_ID,
    F.PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC,
    F.PRODUCT_ID ASC;