-- 코드를 입력하세요
SELECT 
    BOOK_ID, 
    TO_CHAR(
        PUBLISHED_DATE,
        'YYYY-MM-DD'
    ) AS PUBLISHED_DATE
FROM 
    BOOK
WHERE 
    CATEGORY = '인문' 
    AND PUBLISHED_DATE >= TO_DATE('2021-01-01', 'YYYY-MM-DD')
    AND PUBLISHED_DATE < TO_DATE('2022-01-01', 'YYYY-MM-DD')
ORDER BY PUBLISHED_DATE ASC;