-- 코드를 입력하세요
SELECT
    F.PRODUCT_CODE,
    SUM(F.PRICE * S.SALES_AMOUNT) AS SALES
FROM
    PRODUCT F
JOIN
    OFFLINE_SALE S
ON
    F.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    F.PRODUCT_CODE
ORDER BY
    SALES DESC,
    F.PRODUCT_CODE ASC;