WITH USERS AS (
    SELECT 
        COUNT(*) AS CNT
    FROM
        USER_INFO
    WHERE
        TO_CHAR(JOINED, 'YYYY') = '2021'   
)

SELECT
    TO_NUMBER(TO_CHAR(S.SALES_DATE , 'YYYY')) AS YEAR,
    TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH,
    COUNT(DISTINCT (F.USER_ID)) AS PURCHASED_USERS,
    ROUND(
    (1.0*COUNT(DISTINCT (F.USER_ID)))/(
        SELECT
            CNT
        FROM
            USERS
    )
    , 1) 
    AS PUCHASED_RATIO
FROM
    USER_INFO F
JOIN
    ONLINE_SALE S
ON
    F.USER_ID = S.USER_ID
WHERE
    TO_CHAR(F.JOINED, 'YYYY') = '2021'
GROUP BY
    TO_CHAR(S.SALES_DATE , 'YYYY'),
    TO_CHAR(S.SALES_DATE, 'MM')
ORDER BY
    YEAR ASC,
    MONTH ASC