SELECT
    F.PRODUCT_CODE,
    SUM(S.SALES_AMOUNT) * F.PRICE AS SALES
FROM
    PRODUCT F
JOIN
    OFFLINE_SALE S
ON
    F.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    F.PRODUCT_CODE,
    F.PRICE
ORDER BY
    SALES DESC,
    F.PRODUCT_CODE ASC;