SELECT
    F.ID,
    F.GENOTYPE,
    S.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA F
JOIN
    ECOLI_DATA S
ON
    F.PARENT_ID = S.ID
WHERE
    F.GENOTYPE & S.GENOTYPE = S.GENOTYPE
ORDER BY
    F.ID ASC;