-- 코드를 입력하세요
SELECT
    DISTINCT F.CAR_ID AS CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR F
JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY S
ON
    F.CAR_ID = S.CAR_ID
WHERE
    TO_CHAR(S.START_DATE, 'MM') = '10'
    AND
    F.CAR_TYPE = '세단'
ORDER BY
    CAR_ID DESC;