# SELECT
#     I.ITEM_ID,
#     I.ITEM_NAME,
#     I.RARITY
# FROM
#     ITEM_INFO AS I
# JOIN
#     ITEM_TREE AS T
# ON I.ITEM_ID = T.ITEM_ID
# JOIN
#     ITEM_INFO AS I2
# ON 
#     T.PARENT_ITEM_ID = I2.ITEM_ID
# WHERE
#     I2.RARITY = 'RARE'
# ORDER BY
#     I.ITEM_ID DESC;

SELECT
    I.ITEM_ID,
    I.ITEM_NAME,
    I.RARITY
FROM
    ITEM_INFO AS I
JOIN
    ITEM_TREE AS T
ON 
    I.ITEM_ID = T.ITEM_ID
WHERE
    T.PARENT_ITEM_ID IN
        (SELECT
            ITEM_ID
         FROM
            ITEM_INFO
         WHERE
            RARITY = 'RARE'
        )
ORDER BY
    I.ITEM_ID DESC;