SELECT
    S.INGREDIENT_TYPE AS INGREDIENT_TYPE,
    SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF F
JOIN
    ICECREAM_INFO S
ON
    F.FLAVOR = S.FLAVOR
GROUP BY
    S.INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER ASC;