-- 코드를 입력하세요
SELECT
    F.CATEGORY,
    SUM(S.SALES) AS TOTAL_SALES
FROM
    BOOK F
JOIN
    BOOK_SALES S
ON
    F.BOOK_ID = S.BOOK_ID
    AND
    TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY
    F.CATEGORY
ORDER BY
    F.CATEGORY