-- SELECT
--     B.BOOK_ID,
--     A.AUTHOR_NAME,
--     TO_CHAR(B.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
-- FROM
--     BOOK B
-- JOIN
--     AUTHOR A
-- ON
--     B.AUTHOR_ID = A.AUTHOR_ID
--     AND
--     B.CATEGORY = '경제'
-- ORDER BY
--     B.PUBLISHED_DATE ASC;



WITH BOOK_AUTHOR AS (
    SELECT
        *
    FROM
        AUTHOR
)

SELECT 
    BOOK_ID,
    A.AUTHOR_NAME AS AUTHOR_NAME,
    TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM
    BOOK B
JOIN
    BOOK_AUTHOR A
ON
    B.AUTHOR_ID = A.AUTHOR_ID
WHERE
    B.CATEGORY ='경제'
ORDER BY
    PUBLISHED_DATE ASC;
